"""
4-Agent DevOps Pipeline:
  PlannerAgent → CodeAgent → ReviewAgent → ExplainerAgent
"""
from .nova_client import invoke_nova

# ---------------------------------------------------------------------------
# Agent system prompts
# ---------------------------------------------------------------------------

PLANNER_SYSTEM = """You are PlannerAgent, a senior DevOps architect powered by Amazon Nova.
Your job is to take a user's DevOps request and break it into a clear, ordered list of concrete steps.
Focus on AWS services. Be specific about which services to use (ECS, Lambda, EKS, RDS, etc.).
Output a numbered list with brief explanations for each step.
Always end with: > ✅ Plan generated by Nova PlannerAgent"""

CODER_SYSTEM = """You are CodeAgent, an expert infrastructure-as-code engineer powered by Amazon Nova.
Given a DevOps plan, generate the actual code: Terraform HCL, bash scripts, and GitHub Actions YAML.
Always include:
- A terraform/main.tf with all required AWS resources
- A .github/workflows/deploy.yml CI/CD pipeline
Use best practices: variables, outputs, proper IAM, security groups.
Always end with: > ✅ Code generated by Nova CodeAgent"""

REVIEWER_SYSTEM = """You are ReviewAgent, a cloud security and DevOps best-practices expert powered by Amazon Nova.
Review the generated infrastructure code for:
1. Security issues (hardcoded secrets, over-permissive IAM, open ports)
2. AWS best practices (tagging, logging, state management)
3. Reliability concerns (health checks, auto-scaling, rollback)
4. Cost optimization opportunities
Provide a structured review with ✅ passed checks, ⚠️ recommendations, and a security score /10.
Always end with: > ✅ Review completed by Nova ReviewAgent"""

EXPLAINER_SYSTEM = """You are ExplainerAgent, a technical writer powered by Amazon Nova.
Your job is to explain the generated DevOps pipeline in plain English that a developer (not a DevOps expert) can understand.
Explain: what each step does, why it matters, and what happens automatically after setup.
Use analogies, avoid jargon, and be encouraging.
Always end with: > ✅ Explanation by Nova ExplainerAgent"""


# ---------------------------------------------------------------------------
# Agent functions
# ---------------------------------------------------------------------------

def run_planner(user_request: str) -> str:
    return invoke_nova(PLANNER_SYSTEM, f"DevOps request: {user_request}")


def run_coder(plan: str, user_request: str) -> str:
    prompt = f"""Original request: {user_request}

Pipeline plan:
{plan}

Generate the Terraform and GitHub Actions code for this pipeline."""
    return invoke_nova(CODER_SYSTEM, prompt)


def run_reviewer(code: str, plan: str) -> str:
    prompt = f"""Review this generated infrastructure code:

{code}

Context (original plan):
{plan}"""
    return invoke_nova(REVIEWER_SYSTEM, prompt)


def run_explainer(plan: str, code: str, review: str, user_request: str) -> str:
    prompt = f"""Explain this DevOps pipeline in plain English.

Original request: {user_request}

Plan:
{plan}

Generated code summary:
{code[:500]}...

Review findings:
{review[:500]}..."""
    return invoke_nova(EXPLAINER_SYSTEM, prompt)


# ---------------------------------------------------------------------------
# Full pipeline orchestrator
# ---------------------------------------------------------------------------

def run_pipeline(user_request: str) -> dict:
    """Run all 4 agents in sequence and return results."""
    results = {}

    # Agent 1: Planner
    results["planner"] = run_planner(user_request)

    # Agent 2: Coder
    results["coder"] = run_coder(results["planner"], user_request)

    # Agent 3: Reviewer
    results["reviewer"] = run_reviewer(results["coder"], results["planner"])

    # Agent 4: Explainer
    results["explainer"] = run_explainer(
        results["planner"],
        results["coder"],
        results["reviewer"],
        user_request,
    )

    return results
